# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 125892a4fcf880a4045347b206cd96f01a95edb4d1920526b832efe0976f4788bd19696e26f03f31ca5ad94aae3ab113a05e2374802cecbadf1408f17e608c56

test:
  secret_key_base: 1334624e2cca75d694c1b1c4045c27c08013fff1a08215050e0f1c5143fc7781cc0edb2d2b403bcad2270ae51cbb691929ca7c02b37e39561c6bcf0cc860316b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
